apiVersion: v1
kind: Service
metadata:
  name: os-mcp-lb
  namespace: panda-os
  annotations:
    metallb.io/address-pool: sdf-services
spec:
  type: LoadBalancer
  allocateLoadBalancerNodePorts: false
  selector:
    app: os-mcp-server
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
