apiVersion: v1
kind: Secret
metadata:
  name: opensearch-credentials
type: Opaque
stringData:
  host: "FIXME"
  port: "FIXME"
  username: "FIXME"
  password: "FIXME"
  knn_index: "FIXME"
  completed_index: "FIXME"
  running_index: "FIXME"
  api_key: "FIXME"
  api_key_name: "FIXME"
